= MongoDB Dump and Restore

    printjsononeline(cursor.next());

printjson

== 초록(Abstract)
MongoDB에서 Aggregation Query를 Dump하고 Restore하기

== 방법 1
. Aggregation 맨 마지막에 out 사용

.결과를 results collection으로 출력하는 예시
db.collection.aggregate( [ { aggregation steps... }, { $out : "results" } ] )

. mongoexport로 출력
mongoexport -d database -c results -f field1,field2,etc --csv > results.csv

. collection drop
db.results.drop()


https://stackoverflow.com/a/25936760


== 방법 2
mongodb://dev-db-common.devel.kakao.com:27017
mongo --nodb --eval < ./abc.js >> ./hello.json

db.getCollection("irregularMatchRule").aggregate(
    [
        {
            "$lookup" : {
                "from" : "intent",
                "localField" : "intentId",
                "foreignField" : "_id",
                "as" : "intent"
            }
        },
        {
            "$match" : {
                "intent.0" : {
                    "$exists" : 0
                }
            }
        }
    ],
    {
        "allowDiskUse" : false
    }
)

load('config.js');

conn = new Mongo(DB_BUILDER_URI);
db = conn.getDB('builder');

// db.getCollection("irregularMatchRule").aggregate(
//     [
//         {
//             "$lookup" : {
//                 "from" : "intent",
//                 "localField" : "intentId",
//                 "foreignField" : "_id",
//                 "as" : "intent"
//             }
//         },
//         {
//             "$match" : {
//                 "intent.0" : {
//                     "$exists" : 0
//                 }
//             }
//         }
//     ],
//     {
//         "allowDiskUse" : false
//     }
// );

db.getCollection("irregularMatchRule").aggregate(
    [
        {
            "$match" : {
                "intentId" : "5e588941d635f700012e230e:e"
            }
        }
    ],
    {
        "allowDiskUse" : false
    }
).forEach(function(doc) {
    print(JSON.stringify(doc));
});

